<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HealthChecks.ClickHouse\HealthChecks.ClickHouse.csproj" />
      <ProjectReference Include="..\HealthChecks.CockroachDb\HealthChecks.CockroachDb.csproj" />
      <ProjectReference Include="..\HealthChecks.Couchbase\HealthChecks.Couchbase.csproj" />
      <ProjectReference Include="..\HealthChecks.Db2\HealthChecks.Db2.csproj" />
      <ProjectReference Include="..\HealthChecks.Elasticsearch\HealthChecks.Elasticsearch.csproj" />
      <ProjectReference Include="..\HealthChecks.Exasol\HealthChecks.Exasol.csproj" />
      <ProjectReference Include="..\HealthChecks.Greenplum\HealthChecks.Greenplum.csproj" />
      <ProjectReference Include="..\HealthChecks.Kafka\HealthChecks.Kafka.csproj" />
      <ProjectReference Include="..\HealthChecks.MongoDb\HealthChecks.MongoDb.csproj" />
      <ProjectReference Include="..\HealthChecks.MsSql\HealthChecks.MsSql.csproj" />
      <ProjectReference Include="..\HealthChecks.MySql\HealthChecks.MySql.csproj" />
      <ProjectReference Include="..\HealthChecks.NpgSql\HealthChecks.NpgSql.csproj" />
      <ProjectReference Include="..\HealthChecks.Oracle\HealthChecks.Oracle.csproj" />
      <ProjectReference Include="..\HealthChecks.Redis\HealthChecks.Redis.csproj" />
      <ProjectReference Include="..\HealthChecks.Sqlite\HealthChecks.Sqlite.csproj" />
    </ItemGroup>

</Project>
